### PR TITLE
Merge vpicaver's fork

### PR DESCRIPTION
**Pull request by vpicaver**

### CODE REVIEW

**Comment by vpicaver** [comment]
This fixes multiple bugs found in the master. @benlau do you think you can review this and merge it in so we can close some of the existing bugs?

**Comment by vpicaver** [comment]
@benlau Do you have any suggestions on what I need to go to get this merged?

**Comment by benlau** [comment]
> @benlau Do you have any suggestions on what I need to go to get this merged?

Hi @vpicaver,

Thanks for the patch and sorry for keeping you waiting. In fact, I am scheduling a time to review the changes but unfortunately, I was too busy last week. Hopefully, I could respond this week.

**Comment by vpicaver** [comment]
Awesome thanks!

**Pull request merged**
